### ISSUE TITLE
Reading history when neovim restart

### ISSUE THREAD

**Issue by kdurant** [AckslD/nvim-neoclip.lua#18] opened 2021-09-02 05:43 UTC
When I use 'Telescope neoclip` after neovim restart, There is nothing in Telescope windows.

**Comment by AckslD** [comment] 2021-09-02 17:42
Hi @kdurant! I think this might be a duplicate of #16?

**Comment by AckslD** [comment] 2021-09-14 13:25
Closing due to inactivity, feel free to open again if you still have an issue which is not covered by #16

**Closed** 2021-09-14 13:25 UTC
