### ISSUE TITLE
Auto paste on entry select

### ISSUE THREAD

**Issue by JoseConseco** [AckslD/nvim-neoclip.lua#2] opened 2021-08-16 21:52 UTC
Hi neoclip is great  - nvim was missing yank history with  menu.
One problem in have 
 -  open  telescope neoclip - press `ESC` - we go into prompt normal mode in telescope - now j,k keys can be used to navigate yank list - but pressing enter wont override "  register  (neoclip works ok using arrows keys though in the prompt insert mode). 

It would be cool if we had option to automatically paste selected item on `ret` or other key.

Lastly using:
`:lua require('telescope').extensions.neoclip.default({initial_mode = 'normal'})<CR>`
Wont populate yank list  (but I think it may be telescope bug,  - already reported by someone here https://github.com/nvim-telescope/telescope.nvim/issues/1018)

**Comment by AckslD** [comment] 2021-08-16 22:18
Hi @JoseConseco! Thanks for reporting and the suggestions! I'll think I know why enter doesn't work in normal mode, will try to fix that.

I agree that adding a keybind (configurable) that instead just pastes instead of replacing the register would be nice to have :+1: 

I'll have to look into the `initial_mode = 'normal'` thing. What is intended to do?

**Comment by fdschmidt93** [comment] 2021-08-17 06:23
> It would be cool if we had option to automatically paste selected item on ret or other key.

There currently is somewhat unexpected behavior with `actions.insert_symbol`, see https://github.com/nvim-telescope/telescope.nvim/issues/1072. Its fix https://github.com/nvim-telescope/telescope.nvim/pull/1117 only needs finishing touches, then what you want is supported supported upstream out-of-the-box.

> I'll have to look into the initial_mode = 'normal' thing. What is intended to do?

It's meant to start the telescope picker in normal mode. I think @JoseConseco uses it to navigate with j,k  rather than `<C-n>, <C-p>`.

> Lastly using:
:lua require('telescope').extensions.neoclip.default({initial_mode = 'normal'})<CR>
Wont populate yank list (but I think it may be telescope bug, - already reported by someone here nvim-telescope/telescope.nvim#1018)

As referred to in your issue, this will be fixed in https://github.com/nvim-telescope/telescope.nvim/pull/987 which will be merged soon :)

**Comment by JoseConseco** [comment] 2021-08-20 21:56
latest telescope update fixed running neoclip in normal mode - the yank list is automatically filled (without need to be in insert mode). I guess we have to wait for inser_symbol fix then for  auto-paste selected item to work?

**Comment by AckslD** [comment] 2021-08-22 11:53
@JoseConseco I added support to paste directly in #9. Let me know it that works for you. It doesn't use telescope (`insert_symbol`) for this yet but we should probably move over to that once it's ready.

**Comment by JoseConseco** [comment] 2021-08-22 15:24
I checked out 'paste-directly' branch but it does not look  auto-paste work.
https://user-images.githubusercontent.com/13521338/130360689-af98ab0f-8736-4faa-b949-93947063c93c.mp4

I selected yank and pressed `enter` to paste.

**Comment by AckslD** [comment] 2021-08-23 01:14
@JoseConseco I'm just so used to clipmenu which has this behaviour but paste directly does also make a lot of sense. Anyway you can configure this to be the what happens with `ret` or any other key through the `setup` funcion. See README for details or let me know if you have questions.

**Closed** 2021-08-23 01:20 UTC
